### ISSUE TITLE
JavaScript of the multistate buttons performs very badly

### ISSUE THREAD

**Issue by markkuriekkinen** [apluslms/mooc-jutut#15]
Reported by @jsorva

Something that I noticed now while working in the new Jutut message 
interface is that page reloads are slow: specifically, the style of the 
new buttons seems to take a bit to load. It's a pretty small thing, I 
guess, but the annoyance does accumulate when you spend hours and hours 
in the system, often refreshing many times per minute while working on 
reducing some list of messages or another. (I read a message or two, 
remove tags, then refresh to update the list of messages that still have 
that tag.)

I didn't check, but is this perhaps because of some external css stuff 
that loads slowly?

The slowness that I mean is that the big array of buttons shows up at 
the top initially "ugly" and only gets the proper style after a few 
seconds. This is more of an issue on the pages where the buttons are 
folded out of sight, since the folding only happens after the style 
loads, which affects the placement of the students messages on screen 
and thereby messes with UX.

**Comment by Mankro** [comment]
Teemu S. suggested the following:
One reason could be that the styling is done with JS and the JS is not run before the whole page is rendered.

**Comment by Mankro** [comment]
Ella's small fix to this issue has been merged to master: https://github.com/apluslms/mooc-jutut/commit/21f4e7d8f78e0db7d5074096da45834b9d4c8ad3
