### ISSUE TITLE
Add a direct link from each Jutut message to the A+ chapter that the message is from

### ISSUE THREAD

**Issue by Mankro** [apluslms/mooc-jutut#29]
O1 J.S. requests:

> Add a direct link from each Jutut message to the A+ chapter that the message is from. 

This feature almost already exists (and has existed for years). The upper right corner of the feedback item contains a grey "A+" button that leads to the full-view assignment page in A+. It should point to the chapter page of the assignment instead if the assignment has been embedded in a chapter. (In the A+ database, embedded assignments have the "status UNLISTED" and the "parent" foreign key points to the chapter learning object. But does the Jutut database include any such data yet?)

![image](https://user-images.githubusercontent.com/6130378/191236148-3115a5cd-548c-45fa-8654-536cad412177.png)

**Comment by Mankro** [comment]
A simple shortcut could be to assume that Jutut feedback questionnaires are always included in A+ chapters and the A+ chapter link in Jutut would be created with that assumption.

**Comment by etanttila** [comment]
Are the Jutut feedback questionnaires always included/embedded in A+ chapters?
Also, it seems like the URLs for the exercises come from the API (the `html_url` field in the exercises object list, e.g. https://plus.cs.aalto.fi/api/v2/exercises/38422/). The exercise API doesn't seem to include a link to the chapter in which the exercise is embedded. However, if can (at least typically) be figured out from the html_url by dropping the last part off. If we would like the page to scroll immediately to the correct part of the page, e.g. https://plus.cs.aalto.fi/o1/2022/w01/ch07/#chapter-exercise-15, we would also need the ID, which is not in the API. 

Should the API be updated to better support linking to the parent page?

**Comment by Mankro** [comment]
> Are the Jutut feedback questionnaires always included/embedded in A+ chapters?

Jutut feedback questionnaires don't have to be embedded in A+ chapters, but I think all courses that use Jutut have done it so. It is, nonetheless, a nonoptimal, "dirty" solution.

Adding new fields to the A+ API is one alternative. It might also be possible to deduce the parent chapter and its HTML URL from the tree API. The "tree" reveals the hierarchical structure of the course, thus children are listed under their parents.
For example, https://plus.cs.aalto.fi/api/v2/courses/169/tree/
Though, at a quick glance, it looks like that the tree API does not show the HTML URLs for the chapters and the exercise detail API only includes submittable assignments, not any chapters.

**Comment by etanttila** [comment]
Would it be better for the link to the chapter to lead to the top of the chapter or to the part where the exercise is embedded (most commonly on the bottom of the page for feedbacks)? One isn't really more difficult to implement than the other.

If a feedback questionnaire is not embedded in a chapter, we probably want the link to direct the user to the exercise page rather than the previous chapter or the module, correct?

**Comment by Mankro** [comment]
> Would it be better for the link to the chapter to lead to the top of the chapter or to the part where the exercise is embedded (most commonly on the bottom of the page for feedbacks)? One isn't really more difficult to implement than the other.

My guess is to link to the exercise part, which means the chapter URL ends with the anchor like `#chapter-exercise-5`.
@jsorva, what do you think?

> If a feedback questionnaire is not embedded in a chapter, we probably want the link to direct the user to the exercise page rather than the previous chapter or the module, correct?

Yes, the exercise page is the only sensible target in this case.

**Comment by Mankro** [comment]
@etanttila an old duplicate issue has comments about this:
https://github.com/apluslms/a-plus/issues/456

**Comment by etanttila** [comment]
Thanks, that should make it quite nice, as one could just use the method `get_display_url` in Aplus of the learning object. In the issue you linked, Jaakko had suggested the following:

> I think it should be fine to replace the html_url in the API with the correct url, which points to the exercise within the chapter (i.e. one that includes the fragment)

Does any other service require the `html_url` in the API to link to the exercise page rather than the embedded chapter? And if it would be ok to replace the `html_url` with the suggested implementation, can this be done for all exercises or should it be done for only feedback questionnaires?

**Comment by Mankro** [comment]
> Does any other service require the `html_url` in the API to link to the exercise page rather than the embedded chapter? 

Probably not. The html url is anyway intended for humans browsing the web site. No script is supposed to use the html url for fetching machine-readable data. When the exercise is embedded in a chapter, users are normally expected to read the chapter page and not bypass it by going directly to the full-view exercise page.

> And if it would be ok to replace the html_url with the suggested implementation, can this be done for all exercises or should it be done for only feedback questionnaires?
>
> Or would it be better to just add another field, e.g. "display_url", so the API stays backwards compatible?

Replace `html_url` with the suggestion for all exercises when they are embedded in a chapter.
