### ISSUE TITLE
Indicate to staff whether a staff response has been received by a student

### ISSUE THREAD

**Issue by jsorva** [apluslms/mooc-jutut#40]
It would be lovely to see, and a glance, whether each Jutut message that is displayed (in any Jutut view) has or has not been already received/read by the student. (I mean, a “best guess“ as to whether the message has been shown in A+ to the student.) 

I expect that, given A+’s design, an implementation would be rather a lot of work. It would nevertheless be great to see this work one day. 

(Before we had A+, we had Goblin, where this worked very nicely. Messages that had been received had a different background color than others.)

**Comment by Mikael-Lenander** [comment]
Working on this
