### ISSUE TITLE
Button for cancelling editing of message depends on whether content was empty or not

### ISSUE THREAD

**Issue by etanttila** [apluslms/mooc-jutut#51]
When the teacher is writing a response, the button for cancelling the edit depends on whether there was text before in the textbox or not. If the response was empty, it says "Reset", if it contained text, it says "Cancel". Is this desired behaviour?

If the feedback was empty:
![image](https://github.com/apluslms/mooc-jutut/assets/50318434/b898f4be-7aa6-449b-891e-9b170718698e)
If it had text beforehand:
![image](https://github.com/apluslms/mooc-jutut/assets/50318434/2e0526fe-191c-4065-84df-884f60d68bc8)

This may not be an issue, just behavior that I (and Otto S.) found surprising.

**Comment by Mankro** [comment]
I haven't noticed this before. It looks weird. If the button always cancels the teacher's response, then wouldn't it be more clear to call the button "cancel"? "Reset" has some other meanings too that don't fit here.
