### ISSUE TITLE
Crash when parsing localized strings

### ISSUE THREAD

**Issue by PasiSa** [apluslms/mooc-jutut#73]
Jutut crashes when trying to parse localized text on a multilingual course, in lib/helpers.py, [str_in_selected_language](https://github.com/apluslms/mooc-jutut/blob/017cd675d421c2c196c4323e211ef16934219da6/lib/helpers.py#L17). The backtrace ends as follows:

  File "/srv/jutut/venv/lib/python3.8/site-packages/django/template/base.py", line 847, in resolve
    value = self._resolve_lookup(context)
  File "/srv/jutut/venv/lib/python3.8/site-packages/django/template/base.py", line 890, in _resolve_lookup
    current = getattr(current, bit)
  File "/srv/jutut/mooc-jutut/feedback/models.py", line 194, in context_name
    return str_in_selected_language(s)
  File "/srv/jutut/mooc-jutut/lib/helpers.py", line 28, in str_in_selected_language
    lang_alts = dict(map(

One question that comes to mind: Apparently this is pretty much the same functionality as [pick_localized](https://github.com/apluslms/a-plus/blob/a932c5104504f3367e81448ca8a42584f88f27a1/lib/localization_syntax.py#L13) in aplus front. Why not just reuse that implementation also here?

**Comment by Mankro** [comment]
I assume that this error message is part of the same log that you were looking at:
```
Internal Server Error: /manage/COURSEID/feedbacks/
ValueError at /manage/COURSEID/feedbacks/
dictionary update sequence element #0 has length 3; 2 is required
```

@jsorva this error is repeated in the logs now that you are trying to do something.

**Comment by Mankro** [comment]
https://github.com/apluslms/mooc-jutut/blob/017cd675d421c2c196c4323e211ef16934219da6/lib/helpers.py#L29
`s.split(':', 1)`
Limiting the number of splits so that only the first colon is used seems like a decent quick workaround.
