### ISSUE TITLE
Date strings are poorly formatted

### ISSUE THREAD

**Issue by jsorva** [apluslms/mooc-jutut#78]
Before the recent UI update, Jutut would display time-and-date info on messages nicely. (I think it was something like "X days and X hours ago".) 

After the update, dates are in an awkward U.S. format where it’s unclear which is the month and which is the year. (See below.)

![image](https://github.com/apluslms/mooc-jutut/assets/8523129/16c04d9f-18ad-4dc0-91d7-d5b4fe847ef0)

Let’s please use a different format for dates, at least, or maybe go back to the "X hours ago" type of thing, which worked fine.

(This is not urgent but I hope it can be fixed at some point.)

**Comment by ihalaij1** [comment]
@jsorva I made some changes in PR #81. What do you think of the changes?

**Comment by jsorva** [comment]
> @jsorva I made some changes in PR #81. What do you think of the changes?

Looks good! 👍
