### ISSUE TITLE
Number-of-messages-found UI string could be improved

### ISSUE THREAD

**Issue by jsorva** [apluslms/mooc-jutut#79]
This is not very important at all, but I thought I’d throw it out here.

Before the recent UI update, the Jutut interface was structured in terms of individual *messages*. It is now structured in terms of *conversations*, each of which may include multiple messages from the same student. (This is much better.)

Perhaps the found-message count at the top of pages could be updated to reflect this redesign. For example, where it says "4 messages found", below, perhaps it could instead say "4 student messages in 3 conversations found", or something of the sort.

![image](https://github.com/apluslms/mooc-jutut/assets/8523129/2b2c0740-52f3-4374-9b25-3a6f7755c691)

**Comment by jsorva** [comment]
This is now better than before — thanks, @ihalaij1!

One thing, though. When there’s multiple pages of results, the UI string is now funny:

![image](https://github.com/apluslms/mooc-jutut/assets/8523129/1130f501-7559-467d-9dd2-0b0a4c256a9b)

That is, the "conversation count" only counts the currently visible ones.

**Comment by jsorva** [comment]
Oh, and while I’m commenting on this issue, here’s some more bikeshedding: 
After working with the new UI for a while, I’m starting to feel that 
"X conversations found with a total of Y messages" is a slightly better phrasing than 
"Y student messages in X conversations found". It’s the conversation count that is more significant in the new UI, so that should come first.

**Comment by Mankro** [comment]
New issue from the recent comments: #94
