### ISSUE TITLE
Teacher response UI is painful to use on mobile

### ISSUE THREAD

**Issue by jsorva** [apluslms/mooc-jutut#90]
The text are where teachers respond to student is really tiny, at least in my context. It’s really hard to use at the default width, and resizing it doesn’t seem to work either (at least on mobile; it does now work on desktop since #77’s been fixed — thanks!)

Below is a pic of how it looks like on my iPhone. Note the difficult-to-read student message, the tiny response box, and the way the buttons are hard to click because of the "not saved" stuff floating on top.

Rotating the phone 90 degrees alleviates the problem, but there is then a severe problem in the vertical direction, plus it’s really awkward to type with the phone in landscape.

![jutut_narrow](https://github.com/apluslms/mooc-jutut/assets/8523129/849464a3-8f09-413e-9b02-7f3e877c1d01)

**Comment by etanttila** [comment]
That indeed is a bug, the response box was supposed to be full width (with tags displayed below) when the screen is smaller than 700px, however, the styling unfortunately didn't work (I'm so sorry about that)! I made a [minor commit ](https://github.com/apluslms/mooc-jutut/commit/43aef9ff34a7f7c602b9856487980f02776fa877) that should fix it, I'll create a PR in the near future (and possibly include some other minor fixes as well in that).
