### ISSUE TITLE
Number-of-messages-found UI string should include all results/pages and the wording is a bit awkward

### ISSUE THREAD

**Issue by markkuriekkinen** [apluslms/mooc-jutut#94]
From #79:

This is now better than before — thanks, @ihalaij1!

One thing, though. When there’s multiple pages of results, the UI string is now funny:

![image](https://github.com/apluslms/mooc-jutut/assets/8523129/1130f501-7559-467d-9dd2-0b0a4c256a9b)

That is, the "conversation count" only counts the currently visible ones.

_Originally posted by @jsorva in https://github.com/apluslms/mooc-jutut/issues/79#issuecomment-1741850607_

--> the count should include all records (from all pages).

----------------------------

> Oh, and while I’m commenting on this issue, here’s some more bikeshedding: After working with the new UI for a while, I’m starting to feel that "X conversations found with a total of Y messages" is a slightly better phrasing than "Y student messages in X conversations found". It’s the conversation count that is more significant in the new UI, so that should come first.

_Originally posted by @jsorva  https://github.com/apluslms/mooc-jutut/issues/79#issuecomment-1741850623_

--> change the wording

**Comment by etanttila** [comment]
Clarifying question @jsorva: The message count is not the total feedback count displayed but rather the number of messages that fill the filtering criteria. For example, if one searches for feedback that has the word "question", and in one feedback for a chapter the user has used the word, but in the same conversation there are other messages from the user, all of them appear in the conversation (with the non-results a bit darker), but the non-result messages are not counted in the how many messages are found. Knowing this, which of these in your opinion would be the best (after the conversation count is also fixed to reflect the actual total conversation count):
(1) The current "Y student messages found in X conversations. " (Suomeksi "Y opiskelijan palautetta löytyi X keskustelusta
(2) "X conversations found with a total of Y student messages" as you suggested. (Suomeksi esimerkiksi "X keskustelua löytyi, joissa on yhteensä Y palautetta opiskelijoilta". ) Even though there are more messages in those conversations.
(3) "X conversations found with a total of Y student messages fitting the search criteria" (suomeksi esimerkiksi "X keskustelua löytyi, joissa on yhteensä Y hakuehdot täyttävää palautetta opiskelijoilta.)

The exact wording of course can be finetuned, but which would be the best on the concept level, in your opinion? (And of course if you have better suggestions for the wording, please share them!)

**Comment by jsorva** [comment]
I don’t have strong feelings about this wording. Maybe something like the third one is best? But perhaps it can be shortened a bit. Something like this:

"X conversations found with Y matching student messages." 
"Löytyi X keskustelua ja niissä Y hakuehtoihin osuvaa opiskelijan viestiä."

(Perhaps it would be possible to omit "student" / "opiskelijan", too.)

**Comment by etanttila** [comment]
Thanks, sounds good! I also considered omitting the "student", but then it might not be clear that it's counting only the student messages, not the teacher responses.
